matrix:
  include:
  - language: go
    go: "1.11"

env:
  - GO111MODULE=on

script:
  - go install
  - make

before_install:
  - go get github.com/mitchellh/gox
  - go get go-hep.org/x/hep/groot

after_success:
  - if [ ! -z "$TRAVIS_TAG" ]; then gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"; fi
